fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref:  '1.4.3'
    hocon:
      repo: 'https://github.com/puppetlabs/puppetlabs-hocon.git'
      ref:  '0.9.4'
  symlinks:
    puppetserver: "#{source_dir}"
